--- #YAML:1.0
name:               FFmpeg-Thumbnail
version:            0.01
abstract:           Create a thumbnail from a video
author:
    - Brian Sauls <bbqsauls@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Capture::Tiny:    0.01
    FFmpeg::Command:  0.15
    Moose:            1.14
    Regexp::Common:   2.111
    Test::More:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
